service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]

extensions:
  jaeger_query:
    storage:
      traces: some_storage
      metrics: some_metrics_storage
    ui:
      config_file: /etc/jaeger/ui-config.json

  jaeger_storage:
    backends:
      some_storage:
        memory:
          max_traces: 100000
    metric_backends:
      some_metrics_storage:
        prometheus:
          endpoint: http://prometheus:9090
          normalize_calls: true
          normalize_duration: true

  healthcheckv2:
    http:
      endpoint: "localhost:13133"

connectors:
  spanmetrics:
    dimensions:
      - name: operation

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  jaeger_storage_exporter:
    trace_storage: some_storage

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  jaeger:
    protocols:
      grpc:
        endpoint: "0.0.0.0:14250"
      thrift_http:
        endpoint: "0.0.0.0:14268"

  zipkin:
    endpoint: "0.0.0.0:9411"

processors:
  batch:
